Add ReportErr trait
lemunozm/termchat pull request #20
Opened 2020-11-26 16:08 UTC by sigmaSd

This a trait to simplify reporting recoverable errors to the user.

This is a debatable idea though.

2020-11-26 16:30 UTC, lemunozm commented
Wow! It is really cool!! `report_if_err` leaves the code very clean :)

2020-11-26 16:37 UTC, sigmaSd commented
Cool! I think the same, what do you think about changing it to Report and add a report_info method?

2020-11-26 16:42 UTC, sigmaSd commented
like https://github.com/lemunozm/termchat/compare/master...sigmaSd:generalize?expand=1

2020-11-26 17:06 UTC, lemunozm commented
I like it :)

I would name it `SystemReport` (because System is the actor in all of these cases), or even `Reportable` as an attribute of the system: "Something is Reportable if the system can report it"

And it could could contain:
- `report_info`
- `report_err`
- `report_if_err`
- `report_warn`

2020-11-26 17:19 UTC, sigmaSd commented
Ok I added your suggestions

2020-11-30 12:14 UTC, lemunozm requested changes
I like so much!

I am preparing a breaking API version in `message-io`. The `send` and `send_all` methods do not return an Error. Now: 
 - It panics at some dev misuses.
 - It tries to send the entire data.
 - It generates a RemoveEndopoint Event if the socket brokes.

The `report_if_err` of  `send`/`send_all` methods after these changes shall notify in RemoveEndpoint Event. In future versions probably send methods will return an id of sending. And RemoveEndpoint will return the last sending id confirmed. By now I think that it is fine with the current Disconnection notification.

2020-11-30 12:14 UTC, lemunozm commented on src/util.rs
> +        state.add_system_info_message(self);
```suggestion
        state.add_system_warn_message(self);
```

2020-12-02 08:02 UTC, lemunozm commented on src/application.rs
> +                            try_write().report_if_err(&mut self.state);
Looks really cool!

2020-12-02 08:03 UTC, lemunozm approved these changes

2020-12-02 08:04 UTC, merged